"""
PDF报告生成模块
用于生成ESG合规报告
"""

from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib.units import cm
from io import BytesIO
from datetime import datetime


def generate_pdf_report(data):
    """
    生成ESG合规报告PDF
    
    参数:
        data: 包含公司ESG数据的字典
    
    返回:
        BytesIO: PDF文件的字节流
    """
    
    buffer = BytesIO()
    c = canvas.Canvas(buffer, pagesize=A4)
    width, height = A4
    
    # 设置页边距
    margin_left = 2 * cm
    margin_right = width - 2 * cm
    
    # ========== 第一页：封面 ==========
    
    # 顶部logo区域（绿色背景）
    c.setFillColorRGB(0.15, 0.68, 0.38)
    c.rect(0, height - 5*cm, width, 5*cm, fill=True, stroke=False)
    
    # 标题（白色文字）
    c.setFillColorRGB(1, 1, 1)
    c.setFont("Helvetica-Bold", 28)
    c.drawCentredString(width/2, height - 3*cm, "GreenLink")
    
    c.setFont("Helvetica", 16)
    c.drawCentredString(width/2, height - 4*cm, "ESG Risk Assessment Report")
    
    # 公司名称
    c.setFillColorRGB(0, 0, 0)
    c.setFont("Helvetica-Bold", 20)
    c.drawCentredString(width/2, height - 8*cm, data['company'])
    
    # 报告信息框
    c.setStrokeColorRGB(0.8, 0.8, 0.8)
    c.setLineWidth(1)
    c.rect(margin_left, height - 12*cm, margin_right - margin_left, 3*cm, fill=False, stroke=True)
    
    c.setFont("Helvetica", 11)
    c.drawString(margin_left + 0.5*cm, height - 10*cm, f"Report Date: {datetime.now().strftime('%B %d, %Y')}")
    c.drawString(margin_left + 0.5*cm, height - 10.7*cm, f"Report Type: Supply Chain ESG Compliance")
    c.drawString(margin_left + 0.5*cm, height - 11.4*cm, f"Assessment Period: 2018 - 2023")
    
    # 风险等级概览
    y_pos = height - 15*cm
    c.setFont("Helvetica-Bold", 14)
    c.drawString(margin_left, y_pos, "Risk Level Overview")
    
    y_pos -= 1*cm
    
    # 环境风险
    c.setFont("Helvetica", 11)
    c.drawString(margin_left + 0.5*cm, y_pos, "Environmental Risk (E):")
    c.setFont("Helvetica-Bold", 11)
    
    e_level = data['environment']['risk_level']
    if "低" in e_level or "Low" in e_level:
        c.setFillColorRGB(0.15, 0.68, 0.38)
    else:
        c.setFillColorRGB(0.91, 0.30, 0.24)
    
    c.drawString(margin_left + 6*cm, y_pos, f"{e_level} ({data['environment']['risk_score']}/100)")
    
    # 社会风险
    y_pos -= 0.8*cm
    c.setFillColorRGB(0, 0, 0)
    c.setFont("Helvetica", 11)
    c.drawString(margin_left + 0.5*cm, y_pos, "Social Risk (S):")
    c.setFont("Helvetica-Bold", 11)
    
    s_level = data['social']['risk_level']
    if "低" in s_level or "Low" in s_level:
        c.setFillColorRGB(0.15, 0.68, 0.38)
    else:
        c.setFillColorRGB(0.91, 0.30, 0.24)
    
    c.drawString(margin_left + 6*cm, y_pos, f"{s_level} ({data['social']['risk_score']}/100)")
    
    # 页脚
    c.setFillColorRGB(0.5, 0.5, 0.5)
    c.setFont("Helvetica-Oblique", 8)
    c.drawCentredString(width/2, 2*cm, "Page 1 | Confidential")
    c.drawCentredString(width/2, 1.5*cm, "Generated by GreenLink Platform | www.greenlink.com")
    
    c.showPage()
    
    # ========== 第二页：详细分析 ==========
    
    y_pos = height - 3*cm
    
    # 页眉
    c.setFont("Helvetica-Bold", 16)
    c.setFillColorRGB(0, 0, 0)
    c.drawString(margin_left, y_pos, "Detailed Risk Analysis")
    
    y_pos -= 0.3*cm
    c.setStrokeColorRGB(0.15, 0.68, 0.38)
    c.setLineWidth(2)
    c.line(margin_left, y_pos, margin_right, y_pos)
    
    y_pos -= 1.5*cm
    
    # === 环境风险部分 ===
    c.setFillColorRGB(0.15, 0.68, 0.38)
    c.setFont("Helvetica-Bold", 14)
    c.drawString(margin_left, y_pos, "1. Environmental Risk Assessment (E)")
    
    y_pos -= 0.8*cm
    c.setFillColorRGB(0, 0, 0)
    c.setFont("Helvetica-Bold", 11)
    c.drawString(margin_left + 0.5*cm, y_pos, "Analysis Method:")
    c.setFont("Helvetica", 10)
    c.drawString(margin_left + 4*cm, y_pos, data['environment']['analysis']['method'])
    
    y_pos -= 0.6*cm
    c.setFont("Helvetica-Bold", 11)
    c.drawString(margin_left + 0.5*cm, y_pos, "Analysis Period:")
    c.setFont("Helvetica", 10)
    c.drawString(margin_left + 4*cm, y_pos, data['environment']['analysis']['period'])
    
    y_pos -= 0.8*cm
    c.setFont("Helvetica-Bold", 11)
    c.drawString(margin_left + 0.5*cm, y_pos, "Conclusion:")
    
    y_pos -= 0.6*cm
    c.setFont("Helvetica", 10)
    
    # 文本换行处理
    conclusion = data['environment']['analysis']['evidence']['conclusion']
    max_width = 16 * cm
    
    words = conclusion.split()
    line = ""
    for word in words:
        test_line = line + word + " "
        if c.stringWidth(test_line, "Helvetica", 10) > max_width:
            c.drawString(margin_left + 1*cm, y_pos, line)
            y_pos -= 0.5*cm
            line = word + " "
        else:
            line = test_line
    if line:
        c.drawString(margin_left + 1*cm, y_pos, line)
    
    y_pos -= 1.5*cm
    
    # === 社会风险部分 ===
    c.setFillColorRGB(0.91, 0.30, 0.24)
    c.setFont("Helvetica-Bold", 14)
    c.drawString(margin_left, y_pos, "2. Social Risk Assessment (S)")
    
    y_pos -= 0.8*cm
    c.setFillColorRGB(0, 0, 0)
    c.setFont("Helvetica-Bold", 11)
    c.drawString(margin_left + 0.5*cm, y_pos, "Key Risk Events:")
    
    y_pos -= 0.6*cm
    
    # 显示最多3个关键事件
    c.setFont("Helvetica", 9)
    for idx, event in enumerate(data['social']['key_events'][:3]):
        if y_pos < 5*cm:
            c.showPage()
            y_pos = height - 3*cm
        
        c.setFont("Helvetica-Bold", 9)
        c.drawString(margin_left + 1*cm, y_pos, f"Event {idx+1}: {event['date']}")
        
        y_pos -= 0.5*cm
        c.setFont("Helvetica", 9)
        
        event_text = event['event']
        if len(event_text) > 80:
            event_text = event_text[:80] + "..."
        
        words = event_text.split()
        line = ""
        for word in words:
            test_line = line + word + " "
            if c.stringWidth(test_line, "Helvetica", 9) > 15*cm:
                c.drawString(margin_left + 1.5*cm, y_pos, line)
                y_pos -= 0.4*cm
                line = word + " "
            else:
                line = test_line
        if line:
            c.drawString(margin_left + 1.5*cm, y_pos, line)
        
        y_pos -= 0.4*cm
        impact_text = event['impact'][:60] + "..." if len(event['impact']) > 60 else event['impact']
        c.drawString(margin_left + 1.5*cm, y_pos, f"Impact: {impact_text}")
        
        y_pos -= 0.8*cm
    
    # 页脚
    c.setFillColorRGB(0.5, 0.5, 0.5)
    c.setFont("Helvetica-Oblique", 8)
    c.drawCentredString(width/2, 2*cm, "Page 2 | Confidential")
    
    c.showPage()
    
    # ========== 第三页：建议措施 ==========
    
    y_pos = height - 3*cm
    
    c.setFont("Helvetica-Bold", 16)
    c.setFillColorRGB(0, 0, 0)
    c.drawString(margin_left, y_pos, "Recommended Actions")
    
    y_pos -= 0.3*cm
    c.setStrokeColorRGB(0.15, 0.68, 0.38)
    c.setLineWidth(2)
    c.line(margin_left, y_pos, margin_right, y_pos)
    
    y_pos -= 1.5*cm
    
    c.setFillColorRGB(0, 0, 0)
    c.setFont("Helvetica-Bold", 12)
    c.drawString(margin_left, y_pos, "Immediate Actions:")
    
    y_pos -= 0.8*cm
    
    recommendations = [
        "1. Conduct comprehensive supplier audit within 30 days",
        "2. Engage with supplier on ESG improvement plans",
        "3. Evaluate alternative sourcing strategies",
        "4. Review supply chain risk management policies"
    ]
    
    c.setFont("Helvetica", 11)
    for rec in recommendations:
        c.drawString(margin_left + 0.5*cm, y_pos, rec)
        y_pos -= 0.7*cm
    
    # 页脚
    c.setFillColorRGB(0.5, 0.5, 0.5)
    c.setFont("Helvetica-Oblique", 8)
    c.drawCentredString(width/2, 2*cm, "Page 3 | Confidential")
    
    c.save()
    
    buffer.seek(0)
    return buffer
